import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./store/StoreProvider";
import { ConfigProvider } from "antd";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ConfigProvider
            theme={{
              token: {
                fontFamily: 'Poppins'
              }
            }}>
              <Toaster position="bottom-center" />
            {children}
          </ConfigProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
